export const products = [
  {
    id: 1,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/13/800/800",
    price: 9999,
  },
  {
    id: 2,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/75/800/800",
    price: 9999,
  },
  {
    id: 3,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/79/800/800",
    price: 9999,
  },
  {
    id: 4,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/73/800/800",
    price: 9999,
  },
  {
    id: 5,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/72/800/800",
    price: 9999,
  },
  {
    id: 6,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/71/800/800",
    price: 9999,
  },
  {
    id: 7,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/74/800/800",
    price: 9999,
  },
  {
    id: 8,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/78/800/800",
    price: 9999,
  },
  {
    id: 9,
    title: "Title 1 ",
    description: "This is description 2",
    url: "https://picsum.photos/id/50/800/800",
    price: 9999,
  },
];
